apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 250Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/nfs
    server: openshift.example.com
  persistentVolumeReclaimPolicy: Recycle