apiVersion: v1
kind: Secret
metadata:
  name: fis-auto-db-secret
type: Opague
data:
  db.name: bW9uZ29kYi5kYXRhYmFzZT10ZXN0Cg==
  db.username: bW9uZ29kYi51c2VyPW9zZVVzZXIK
  db.password: bW9uZ29kYi5wYXNzd29yZD1vcGVuc2hpZnQK
